### PR TITLE
Outputting fv-data MS links + XPath string-ranges to S-GA for #30

### PR DESCRIPTION
**Pull request by ebeshero**
I've run the whole pipeline in this branch, so take a look at the files output in standoff_Spine as the end point. Look for the new `<witDetail>` element holding info about the S-GA files. I think we should add one more processing stage to this as outlined at the end of #30.

### CODE REVIEW

**Comment by Yuying-Jin** [comment]
[surprised]     Jin, Yuying reacted to your message:
________________________________

**Comment by ebeshero** [comment]
WAIT don't merge!!!

**Comment by ebeshero** [comment]
@Yuying-Jin I think this is ready to merge now! I've output the pointers to S-GA webpages now as we discussed here: https://github.com/FrankensteinVariorum/fv-postCollation/issues/30#issuecomment-1636043098 . And I have fixed the issue with __I, __M, and __F as well.

**Comment by ebeshero** [comment]
I'm fixing one more thing: Following the TEI Guidelines, the preference is for abbreviated links to begin with a prefix like this: `<witDetail target="sga:c57/#/p3">` . That lets us define how the links resolve in the `<teiHeader>` using a `<prefixDef>` with a `@matchPattern` and `@replacementPattern` (and requires a `@prefix` too).  I left out the prefix, so I'm just adding it and re-processing C1 to C27.

**Comment by ebeshero** [comment]
@Yuying-Jin Okay, I think this is definitely ready to merge now. Lots of updates here!

**Pull request merged**
